### ISSUE TITLE
TRACKING: Webnative browser extension

### ISSUE THREAD

**Issue by bgins** [webnative-examples/webnative-devtools#2]
The Webnative browser extension provides developers a devtools panel with information for debugging their Webnative applications.

It should display the following information:

- Webnative version
- App namespace
- Username
- Account DID
- Filesystem skeleton
- Possibly more

The information should only be exposed when the developer has set `debug` to `true` when initializing a Webnative program.

### Tasks

- [ ] Set up build
- [ ] Upgrade to Manifest V3
- [ ] Set up communication loop with page
- [ ] Implement devtools panel UI

### Dependencies

- [ ] https://github.com/fission-codes/webnative/issues/460

**Comment by therealjeffg** [comment]
Once we get through Milestone 0.1 we should run the design past nicoth and other relatively engaged devs to get feedback.

**Comment by depatchedmode** [comment]
## Overall

Needs an instructional state "Webnative wasn't detected on this page. You have to set DEBUG to true."

## Filesystem view

We'll start with an event log. Highest value starting point, and simpler to implement.

### Concerns:
+ may not have whole tree
+ performance could be slow loading the whole tree

### Extra credit metadata:
+ CID
+ Creation time
+ Arbitrary metadata input by dev

### Questions Filesystem tree helps answer:
+ Was the file written or not?
+ Builds a mental model for the FS heirarchy 
+ Event log would be helpful — maybe this is where we start
+ Replay the state of the tree across time — probably for a later release

## Capabilities:

Show which resources this app has been granted access to via UCANs.

+ Which authentication strategy was used?
+ More importantly: is this an origin resource or a resource projected into this local file space via a capability
+ From whom was this resource requested? To prep for a future when more than just the auth lobby exists as an authorization provider

**Comment by depatchedmode** [comment]
Okay, here's my pencil sketch:
<img width="943" alt="image" src="https://user-images.githubusercontent.com/84613835/218609562-8a391c43-02d5-409e-b27d-b51030864d6f.png">

And the disconnected state:
<img width="588" alt="image" src="https://user-images.githubusercontent.com/84613835/218609663-e3209a3b-afae-4b08-a414-0c9d120ff8a6.png">

Right now the settings pane would probably not contain much, but I'm following the tab pattern that Vue Devtools uses because we'll expand beyond just the event log in the near future. Was considering tossing some of the more stable session / app data in that pane, but it feels like it would be more ergonomic to have it available in the payload pane next to the event data for ease of access.
